# -*- coding: utf-8 -*-
"""
Nomenklatura NACE - uredni ciselnik, ne nase rozhodnuti.

Zaklad je NACE Rev. 2.1 (= CZ-NACE 2025, nemecka WZ 2025, zavazna revize EU
statistiky od 1.1.2025): 86 divizi, 286 skupin, 650 trid. Na tuhle revizi je
postavena i NACE_VERDIKT v taxonomie.py.

Navic jsou tu kody, ktere existovaly jen ve stare NACE Rev. 2 (= CZ-NACE 2008)
a v 2.1 uz nejsou - rejstriky je porad vraci u zaznamu, ktere nikdo neprepsal.
Nejde o "starsi hodnotu tehoz cisla", ale o dve ruzne soustavy: stejne cislo
muze v kazde znamenat neco jineho (trida 58.12 byla v Rev 2 "vydavani
adresaru", v 2.1 uz "vydavani novin"). Pole `revize` proto rika, ze kterou
soustavu jde, aby to slo ve vystupu rozlisit.

Nazvy jsou anglicke a zamerne se neprekladaji - jsou to citace ciselniku
a preklad by z nich udelal nas text, ktery uz nejde overit proti zdroji.

Zdroj: Eurostat SDMX, codelisty ESTAT/NACE_R2_1 a ESTAT/NACE_R2
  https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/codelist/ESTAT/NACE_R2_1
V ciselniku jsou kody zapsane s pismenem sekce ("J6201"); tady je pismeno
v samostatnem poli, aby slo hledat podle ciselneho kodu tak, jak ho vraci
rejstriky.

Co ktery kod ZNAMENA pro zarazeni dodavatele tenhle soubor neresi - to je
NACE_VERDIKT v taxonomie.py.
"""

# kod sekce -> nazev (NACE Rev. 2.1)
SEKCE = {
    "A": "Agriculture, forestry and fishing",
    "B": "Mining and quarrying",
    "C": "Manufacturing",
    "D": "Electricity, gas, steam and air conditioning supply",
    "E": "Water supply; sewerage, waste management and remediation activities",
    "F": "Construction",
    "G": "Wholesale and retail trade",
    "H": "Transportation and storage",
    "I": "Accommodation and food service activities",
    "J": "Publishing, broadcasting, and content production and distribution activities",
    "K": "Telecommunication, computer programming, consulting, computing infrastructure and other information service activities",
    "L": "Financial and insurance activities",
    "M": "Real estate activities",
    "N": "Professional, scientific and technical activities",
    "O": "Administrative and support service activities",
    "P": "Public administration and defence; compulsory social security",
    "Q": "Education",
    "R": "Human health and social work activities",
    "S": "Arts, sports and recreation",
    "T": "Other service activities",
    "U": "Activities of households as employers and undifferentiated goods- and service-producing activities of households for own use",
}


# ciselny kod -> (nazev, sekce, revize)
NACE = {
    "01": ("Crop and animal production, hunting and related service activities", "A", "2.1"),
    "011": ("Growing of non-perennial crops", "A", "2.1"),
    "0111": ("Growing of cereals, other than rice, leguminous crops and oil seeds", "A", "2.1"),
    "0112": ("Growing of rice", "A", "2.1"),
    "0113": ("Growing of vegetables and melons, roots and tubers", "A", "2.1"),
    "0114": ("Growing of sugar cane", "A", "2.1"),
    "0115": ("Growing of tobacco", "A", "2.1"),
    "0116": ("Growing of fibre crops", "A", "2.1"),
    "0119": ("Growing of other non-perennial crops", "A", "2.1"),
    "012": ("Growing of perennial crops", "A", "2.1"),
    "0121": ("Growing of grapes", "A", "2.1"),
    "0122": ("Growing of tropical and subtropical fruits", "A", "2.1"),
    "0123": ("Growing of citrus fruits", "A", "2.1"),
    "0124": ("Growing of pome fruits and stone fruits", "A", "2.1"),
    "0125": ("Growing of other tree and bush fruits and nuts", "A", "2.1"),
    "0126": ("Growing of oleaginous fruits", "A", "2.1"),
    "0127": ("Growing of beverage crops", "A", "2.1"),
    "0128": ("Growing of spices, aromatic, drug and pharmaceutical crops", "A", "2.1"),
    "0129": ("Growing of other perennial crops", "A", "2.1"),
    "013": ("Plant propagation", "A", "2.1"),
    "0130": ("Plant propagation", "A", "2.1"),
    "014": ("Animal production", "A", "2.1"),
    "0141": ("Raising of dairy cattle", "A", "2.1"),
    "0142": ("Raising of other cattle and buffaloes", "A", "2.1"),
    "0143": ("Raising of horses and other equines", "A", "2.1"),
    "0144": ("Raising of camels and camelids", "A", "2.1"),
    "0145": ("Raising of sheep and goats", "A", "2.1"),
    "0146": ("Raising of swine and pigs", "A", "2.1"),
    "0147": ("Raising of poultry", "A", "2.1"),
    "0148": ("Raising of other animals", "A", "2.1"),
    "015": ("Mixed farming", "A", "2.1"),
    "0150": ("Mixed farming", "A", "2.1"),
    "016": ("Support activities to agriculture and post-harvest crop activities", "A", "2.1"),
    "0161": ("Support activities for crop production", "A", "2.1"),
    "0162": ("Support activities for animal production", "A", "2.1"),
    "0163": ("Post-harvest crop activities and seed processing for propagation", "A", "2.1"),
    "017": ("Hunting, trapping and related service activities", "A", "2.1"),
    "0170": ("Hunting, trapping and related service activities", "A", "2.1"),
    "02": ("Forestry and logging", "A", "2.1"),
    "021": ("Silviculture and other forestry activities", "A", "2.1"),
    "0210": ("Silviculture and other forestry activities", "A", "2.1"),
    "022": ("Logging", "A", "2.1"),
    "0220": ("Logging", "A", "2.1"),
    "023": ("Gathering of wild growing non-wood products", "A", "2.1"),
    "0230": ("Gathering of wild growing non-wood products", "A", "2.1"),
    "024": ("Support services to forestry", "A", "2.1"),
    "0240": ("Support services to forestry", "A", "2.1"),
    "03": ("Fishing and aquaculture", "A", "2.1"),
    "031": ("Fishing", "A", "2.1"),
    "0311": ("Marine fishing", "A", "2.1"),
    "0312": ("Freshwater fishing", "A", "2.1"),
    "032": ("Aquaculture", "A", "2.1"),
    "0321": ("Marine aquaculture", "A", "2.1"),
    "0322": ("Freshwater aquaculture", "A", "2.1"),
    "033": ("Support activities for fishing and aquaculture", "A", "2.1"),
    "0330": ("Support activities for fishing and aquaculture", "A", "2.1"),
    "05": ("Mining of coal and lignite", "B", "2.1"),
    "051": ("Mining of hard coal", "B", "2.1"),
    "0510": ("Mining of hard coal", "B", "2.1"),
    "052": ("Mining of lignite", "B", "2.1"),
    "0520": ("Mining of lignite", "B", "2.1"),
    "06": ("Extraction of crude petroleum and natural gas", "B", "2.1"),
    "061": ("Extraction of crude petroleum", "B", "2.1"),
    "0610": ("Extraction of crude petroleum", "B", "2.1"),
    "062": ("Extraction of natural gas", "B", "2.1"),
    "0620": ("Extraction of natural gas", "B", "2.1"),
    "07": ("Mining of metal ores", "B", "2.1"),
    "071": ("Mining of iron ores", "B", "2.1"),
    "0710": ("Mining of iron ores", "B", "2.1"),
    "072": ("Mining of non-ferrous metal ores", "B", "2.1"),
    "0721": ("Mining of uranium and thorium ores", "B", "2.1"),
    "0729": ("Mining of other non-ferrous metal ores", "B", "2.1"),
    "08": ("Other mining and quarrying", "B", "2.1"),
    "081": ("Quarrying of stone, sand and clay", "B", "2.1"),
    "0811": ("Quarrying of ornamental stone, limestone, gypsum, slate and other stone", "B", "2.1"),
    "0812": ("Operation of gravel and sand pits and mining of clay and kaolin", "B", "2.1"),
    "089": ("Mining and quarrying n.e.c.", "B", "2.1"),
    "0891": ("Mining of chemical and fertiliser minerals", "B", "2.1"),
    "0892": ("Extraction of peat", "B", "2.1"),
    "0893": ("Extraction of salt", "B", "2.1"),
    "0899": ("Other mining and quarrying n.e.c.", "B", "2.1"),
    "09": ("Mining support service activities", "B", "2.1"),
    "091": ("Support activities for petroleum and natural gas extraction", "B", "2.1"),
    "0910": ("Support activities for petroleum and natural gas extraction", "B", "2.1"),
    "099": ("Support activities for other mining and quarrying", "B", "2.1"),
    "0990": ("Support activities for other mining and quarrying", "B", "2.1"),
    "10": ("Manufacture of food products", "C", "2.1"),
    "101": ("Processing and preserving of meat and production of meat products", "C", "2.1"),
    "1011": ("Processing and preserving of meat, except of poultry meat", "C", "2.1"),
    "1012": ("Processing and preserving of poultry meat", "C", "2.1"),
    "1013": ("Production of meat and poultry meat products", "C", "2.1"),
    "102": ("Processing and preserving of fish, crustaceans and molluscs", "C", "2.1"),
    "1020": ("Processing and preserving of fish, crustaceans and molluscs", "C", "2.1"),
    "103": ("Processing and preserving of fruit and vegetables", "C", "2.1"),
    "1031": ("Processing and preserving of potatoes", "C", "2.1"),
    "1032": ("Manufacture of fruit and vegetable juice", "C", "2.1"),
    "1039": ("Other processing and preserving of fruit and vegetables", "C", "2.1"),
    "104": ("Manufacture of vegetable and animal oils and fats", "C", "2.1"),
    "1041": ("Manufacture of oils and fats", "C", "2.1"),
    "1042": ("Manufacture of margarine and similar edible fats", "C", "2.1"),
    "105": ("Manufacture of dairy products and edible ice", "C", "2.1"),
    "1051": ("Manufacture of dairy products", "C", "2.1"),
    "1052": ("Manufacture of ice cream and other edible ice", "C", "2.1"),
    "106": ("Manufacture of grain mill products, starches and starch products", "C", "2.1"),
    "1061": ("Manufacture of grain mill products", "C", "2.1"),
    "1062": ("Manufacture of starches and starch products", "C", "2.1"),
    "107": ("Manufacture of bakery and farinaceous products", "C", "2.1"),
    "1071": ("Manufacture of bread; manufacture of fresh pastry goods and cakes", "C", "2.1"),
    "1072": ("Manufacture of rusks, biscuits, preserved pastries and cakes", "C", "2.1"),
    "1073": ("Manufacture of farinaceous products", "C", "2.1"),
    "108": ("Manufacture of other food products", "C", "2.1"),
    "1081": ("Manufacture of sugar", "C", "2.1"),
    "1082": ("Manufacture of cocoa, chocolate and sugar confectionery", "C", "2.1"),
    "1083": ("Processing of tea and coffee", "C", "2.1"),
    "1084": ("Manufacture of condiments and seasonings", "C", "2.1"),
    "1085": ("Manufacture of prepared meals and dishes", "C", "2.1"),
    "1086": ("Manufacture of homogenised food preparations and dietetic food", "C", "2.1"),
    "1089": ("Manufacture of other food products n.e.c.", "C", "2.1"),
    "109": ("Manufacture of prepared animal feeds", "C", "2.1"),
    "1091": ("Manufacture of prepared feeds for farm animals", "C", "2.1"),
    "1092": ("Manufacture of prepared pet foods", "C", "2.1"),
    "11": ("Manufacture of beverages", "C", "2.1"),
    "110": ("Manufacture of beverages", "C", "2.1"),
    "1101": ("Distilling, rectifying and blending of spirits", "C", "2.1"),
    "1102": ("Manufacture of wine from grape", "C", "2.1"),
    "1103": ("Manufacture of cider and other fruit fermented beverages", "C", "2.1"),
    "1104": ("Manufacture of other non-distilled fermented beverages", "C", "2.1"),
    "1105": ("Manufacture of beer", "C", "2.1"),
    "1106": ("Manufacture of malt", "C", "2.1"),
    "1107": ("Manufacture of soft drinks and bottled waters", "C", "2.1"),
    "12": ("Manufacture of tobacco products", "C", "2.1"),
    "120": ("Manufacture of tobacco products", "C", "2.1"),
    "1200": ("Manufacture of tobacco products", "C", "2.1"),
    "13": ("Manufacture of textiles", "C", "2.1"),
    "131": ("Preparation and spinning of textile fibres", "C", "2.1"),
    "1310": ("Preparation and spinning of textile fibres", "C", "2.1"),
    "132": ("Weaving of textiles", "C", "2.1"),
    "1320": ("Weaving of textiles", "C", "2.1"),
    "133": ("Finishing of textiles", "C", "2.1"),
    "1330": ("Finishing of textiles", "C", "2.1"),
    "139": ("Manufacture of other textiles", "C", "2.1"),
    "1391": ("Manufacture of knitted and crocheted fabrics", "C", "2.1"),
    "1392": ("Manufacture of household textiles and made-up furnishing articles", "C", "2.1"),
    "1393": ("Manufacture of carpets and rugs", "C", "2.1"),
    "1394": ("Manufacture of cordage, rope, twine and netting", "C", "2.1"),
    "1395": ("Manufacture of non-wovens and non-woven articles", "C", "2.1"),
    "1396": ("Manufacture of other technical and industrial textiles", "C", "2.1"),
    "1399": ("Manufacture of other textiles n.e.c.", "C", "2.1"),
    "14": ("Manufacture of wearing apparel", "C", "2.1"),
    "141": ("Manufacture of knitted and crocheted apparel", "C", "2.1"),
    "1410": ("Manufacture of knitted and crocheted apparel", "C", "2.1"),
    "142": ("Manufacture of other wearing apparel and accessories", "C", "2.1"),
    "1421": ("Manufacture of outerwear", "C", "2.1"),
    "1422": ("Manufacture of underwear", "C", "2.1"),
    "1423": ("Manufacture of workwear", "C", "2.1"),
    "1424": ("Manufacture of leather clothes and fur apparel", "C", "2.1"),
    "1429": ("Manufacture of other wearing apparel and accessories n.e.c.", "C", "2.1"),
    "15": ("Manufacture of leather and related products of other materials", "C", "2.1"),
    "151": ("Tanning, dyeing, dressing of leather and fur; manufacture of luggage, handbags, saddlery and harness", "C", "2.1"),
    "1511": ("Tanning, dressing, dyeing of leather and fur", "C", "2.1"),
    "1512": ("Manufacture of luggage, handbags, saddlery and harness of any material", "C", "2.1"),
    "152": ("Manufacture of footwear", "C", "2.1"),
    "1520": ("Manufacture of footwear", "C", "2.1"),
    "16": ("Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials", "C", "2.1"),
    "161": ("Sawmilling and planing of wood; processing and finishing of wood", "C", "2.1"),
    "1611": ("Sawmilling and planing of wood", "C", "2.1"),
    "1612": ("Processing and finishing of wood", "C", "2.1"),
    "162": ("Manufacture of products of wood, cork, straw and plaiting materials", "C", "2.1"),
    "1621": ("Manufacture of veneer sheets and wood-based panels", "C", "2.1"),
    "1622": ("Manufacture of assembled parquet floors", "C", "2.1"),
    "1623": ("Manufacture of other builders' carpentry and joinery", "C", "2.1"),
    "1624": ("Manufacture of wooden containers", "C", "2.1"),
    "1625": ("Manufacture of doors and windows of wood", "C", "2.1"),
    "1626": ("Manufacture of solid fuels from vegetable biomass", "C", "2.1"),
    "1627": ("Finishing of wooden products", "C", "2.1"),
    "1628": ("Manufacture of other products of wood and articles of cork, straw and plaiting materials", "C", "2.1"),
    "17": ("Manufacture of paper and paper products", "C", "2.1"),
    "171": ("Manufacture of pulp, paper and paperboard", "C", "2.1"),
    "1711": ("Manufacture of pulp", "C", "2.1"),
    "1712": ("Manufacture of paper and paperboard", "C", "2.1"),
    "172": ("Manufacture of articles of paper and paperboard", "C", "2.1"),
    "1721": ("Manufacture of corrugated paper, paperboard and containers of paper and paperboard", "C", "2.1"),
    "1722": ("Manufacture of household and sanitary goods and of toilet requisites", "C", "2.1"),
    "1723": ("Manufacture of paper stationery", "C", "2.1"),
    "1724": ("Manufacture of wallpaper", "C", "2.1"),
    "1725": ("Manufacture of other articles of paper and paperboard", "C", "2.1"),
    "18": ("Printing and reproduction of recorded media", "C", "2.1"),
    "181": ("Printing and service activities related to printing", "C", "2.1"),
    "1811": ("Printing of newspapers", "C", "2.1"),
    "1812": ("Other printing", "C", "2.1"),
    "1813": ("Pre-press and pre-media services", "C", "2.1"),
    "1814": ("Binding and related services", "C", "2.1"),
    "182": ("Reproduction of recorded media", "C", "2.1"),
    "1820": ("Reproduction of recorded media", "C", "2.1"),
    "19": ("Manufacture of coke and refined petroleum products", "C", "2.1"),
    "191": ("Manufacture of coke oven products", "C", "2.1"),
    "1910": ("Manufacture of coke oven products", "C", "2.1"),
    "192": ("Manufacture of refined petroleum products and fossil fuel products", "C", "2.1"),
    "1920": ("Manufacture of refined petroleum products and fossil fuel products", "C", "2.1"),
    "20": ("Manufacture of chemicals and chemical products", "C", "2.1"),
    "201": ("Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms", "C", "2.1"),
    "2011": ("Manufacture of industrial gases", "C", "2.1"),
    "2012": ("Manufacture of dyes and pigments", "C", "2.1"),
    "2013": ("Manufacture of other inorganic basic chemicals", "C", "2.1"),
    "2014": ("Manufacture of other organic basic chemicals", "C", "2.1"),
    "2015": ("Manufacture of fertilisers and nitrogen compounds", "C", "2.1"),
    "2016": ("Manufacture of plastics in primary forms", "C", "2.1"),
    "2017": ("Manufacture of synthetic rubber in primary forms", "C", "2.1"),
    "202": ("Manufacture of pesticides, disinfectants and other agrochemical products", "C", "2.1"),
    "2020": ("Manufacture of pesticides, disinfectants and other agrochemical products", "C", "2.1"),
    "203": ("Manufacture of paints, varnishes and similar coatings, printing ink and mastics", "C", "2.1"),
    "2030": ("Manufacture of paints, varnishes and similar coatings, printing ink and mastics", "C", "2.1"),
    "204": ("Manufacture of washing, cleaning and polishing preparations", "C", "2.1"),
    "2041": ("Manufacture of soap and detergents, cleaning and polishing preparations", "C", "2.1"),
    "2042": ("Manufacture of perfumes and toilet preparations", "C", "2.1"),
    "205": ("Manufacture of other chemical products", "C", "2.1"),
    "2051": ("Manufacture of liquid biofuels", "C", "2.1"),
    "2059": ("Manufacture of other chemical products n.e.c.", "C", "2.1"),
    "206": ("Manufacture of man-made fibres", "C", "2.1"),
    "2060": ("Manufacture of man-made fibres", "C", "2.1"),
    "21": ("Manufacture of basic pharmaceutical products and pharmaceutical preparations", "C", "2.1"),
    "211": ("Manufacture of basic pharmaceutical products", "C", "2.1"),
    "2110": ("Manufacture of basic pharmaceutical products", "C", "2.1"),
    "212": ("Manufacture of pharmaceutical preparations", "C", "2.1"),
    "2120": ("Manufacture of pharmaceutical preparations", "C", "2.1"),
    "22": ("Manufacture of rubber and plastic products", "C", "2.1"),
    "221": ("Manufacture of rubber products", "C", "2.1"),
    "2211": ("Manufacture, retreading and rebuilding of rubber tyres and manufacture of tubes", "C", "2.1"),
    "2212": ("Manufacture of other rubber products", "C", "2.1"),
    "222": ("Manufacture of plastics products", "C", "2.1"),
    "2221": ("Manufacture of plastic plates, sheets, tubes and profiles", "C", "2.1"),
    "2222": ("Manufacture of plastic packing goods", "C", "2.1"),
    "2223": ("Manufacture of doors and windows of plastic", "C", "2.1"),
    "2224": ("Manufacture of builders’ ware of plastic", "C", "2.1"),
    "2225": ("Processing and finishing of plastic products", "C", "2.1"),
    "2226": ("Manufacture of other plastic products", "C", "2.1"),
    "23": ("Manufacture of other non-metallic mineral products", "C", "2.1"),
    "231": ("Manufacture of glass and glass products", "C", "2.1"),
    "2311": ("Manufacture of flat glass", "C", "2.1"),
    "2312": ("Shaping and processing of flat glass", "C", "2.1"),
    "2313": ("Manufacture of hollow glass", "C", "2.1"),
    "2314": ("Manufacture of glass fibres", "C", "2.1"),
    "2315": ("Manufacture and processing of other glass, including technical glassware", "C", "2.1"),
    "232": ("Manufacture of refractory products", "C", "2.1"),
    "2320": ("Manufacture of refractory products", "C", "2.1"),
    "233": ("Manufacture of clay building materials", "C", "2.1"),
    "2331": ("Manufacture of ceramic tiles and flags", "C", "2.1"),
    "2332": ("Manufacture of bricks, tiles and construction products, in baked clay", "C", "2.1"),
    "234": ("Manufacture of other porcelain and ceramic products", "C", "2.1"),
    "2341": ("Manufacture of ceramic household and ornamental articles", "C", "2.1"),
    "2342": ("Manufacture of ceramic sanitary fixtures", "C", "2.1"),
    "2343": ("Manufacture of ceramic insulators and insulating fittings", "C", "2.1"),
    "2344": ("Manufacture of other technical ceramic products", "C", "2.1"),
    "2345": ("Manufacture of other ceramic products", "C", "2.1"),
    "235": ("Manufacture of cement, lime and plaster", "C", "2.1"),
    "2351": ("Manufacture of cement", "C", "2.1"),
    "2352": ("Manufacture of lime and plaster", "C", "2.1"),
    "236": ("Manufacture of articles of concrete, cement and plaster", "C", "2.1"),
    "2361": ("Manufacture of concrete products for construction purposes", "C", "2.1"),
    "2362": ("Manufacture of plaster products for construction purposes", "C", "2.1"),
    "2363": ("Manufacture of ready-mixed concrete", "C", "2.1"),
    "2364": ("Manufacture of mortars", "C", "2.1"),
    "2365": ("Manufacture of fibre cement", "C", "2.1"),
    "2366": ("Manufacture of other articles of concrete, plaster and cement", "C", "2.1"),
    "237": ("Cutting, shaping and finishing of stone", "C", "2.1"),
    "2370": ("Cutting, shaping and finishing of stone", "C", "2.1"),
    "239": ("Manufacture of abrasive products and non-metallic mineral products n.e.c.", "C", "2.1"),
    "2391": ("Manufacture of abrasive products", "C", "2.1"),
    "2399": ("Manufacture of other non-metallic mineral products n.e.c.", "C", "2.1"),
    "24": ("Manufacture of basic metals", "C", "2.1"),
    "241": ("Manufacture of basic iron and steel and of ferro-alloys", "C", "2.1"),
    "2410": ("Manufacture of basic iron and steel and of ferro-alloys", "C", "2.1"),
    "242": ("Manufacture of tubes, pipes, hollow profiles and related fittings, of steel", "C", "2.1"),
    "2420": ("Manufacture of tubes, pipes, hollow profiles and related fittings, of steel", "C", "2.1"),
    "243": ("Manufacture of other products of first processing of steel", "C", "2.1"),
    "2431": ("Cold drawing of bars", "C", "2.1"),
    "2432": ("Cold rolling of narrow strip", "C", "2.1"),
    "2433": ("Cold forming or folding", "C", "2.1"),
    "2434": ("Cold drawing of wire", "C", "2.1"),
    "244": ("Manufacture of basic precious and other non-ferrous metals", "C", "2.1"),
    "2441": ("Precious metals production", "C", "2.1"),
    "2442": ("Aluminium production", "C", "2.1"),
    "2443": ("Lead, zinc and tin production", "C", "2.1"),
    "2444": ("Copper production", "C", "2.1"),
    "2445": ("Other non-ferrous metal production", "C", "2.1"),
    "2446": ("Processing of nuclear fuel", "C", "2.1"),
    "245": ("Casting of metals", "C", "2.1"),
    "2451": ("Casting of iron", "C", "2.1"),
    "2452": ("Casting of steel", "C", "2.1"),
    "2453": ("Casting of light metals", "C", "2.1"),
    "2454": ("Casting of other non-ferrous metals", "C", "2.1"),
    "25": ("Manufacture of fabricated metal products, except machinery and equipment", "C", "2.1"),
    "251": ("Manufacture of structural metal products", "C", "2.1"),
    "2511": ("Manufacture of metal structures and parts of structures", "C", "2.1"),
    "2512": ("Manufacture of doors and windows of metal", "C", "2.1"),
    "252": ("Manufacture of tanks, reservoirs and containers of metal", "C", "2.1"),
    "2521": ("Manufacture of central heating radiators, steam generators and boilers", "C", "2.1"),
    "2522": ("Manufacture of other tanks, reservoirs and containers of metal", "C", "2.1"),
    "253": ("Manufacture of weapons and ammunition", "C", "2.1"),
    "2530": ("Manufacture of weapons and ammunition", "C", "2.1"),
    "254": ("Forging and shaping metal and powder metallurgy", "C", "2.1"),
    "2540": ("Forging and shaping metal and powder metallurgy", "C", "2.1"),
    "255": ("Treatment and coating of metals; machining", "C", "2.1"),
    "2551": ("Coating of metals", "C", "2.1"),
    "2552": ("Heat treatment of metals", "C", "2.1"),
    "2553": ("Machining of metals", "C", "2.1"),
    "256": ("Manufacture of cutlery, tools and general hardware", "C", "2.1"),
    "2561": ("Manufacture of cutlery", "C", "2.1"),
    "2562": ("Manufacture of locks and hinges", "C", "2.1"),
    "2563": ("Manufacture of tools", "C", "2.1"),
    "259": ("Manufacture of other fabricated metal products", "C", "2.1"),
    "2591": ("Manufacture of steel drums and similar containers", "C", "2.1"),
    "2592": ("Manufacture of light metal packaging", "C", "2.1"),
    "2593": ("Manufacture of wire products, chain and springs", "C", "2.1"),
    "2594": ("Manufacture of fasteners and screw machine products", "C", "2.1"),
    "2599": ("Manufacture of other fabricated metal products n.e.c.", "C", "2.1"),
    "26": ("Manufacture of computer, electronic and optical products", "C", "2.1"),
    "261": ("Manufacture of electronic components and boards", "C", "2.1"),
    "2611": ("Manufacture of electronic components", "C", "2.1"),
    "2612": ("Manufacture of loaded electronic boards", "C", "2.1"),
    "262": ("Manufacture of computers and peripheral equipment", "C", "2.1"),
    "2620": ("Manufacture of computers and peripheral equipment", "C", "2.1"),
    "263": ("Manufacture of communication equipment", "C", "2.1"),
    "2630": ("Manufacture of communication equipment", "C", "2.1"),
    "264": ("Manufacture of consumer electronics", "C", "2.1"),
    "2640": ("Manufacture of consumer electronics", "C", "2.1"),
    "265": ("Manufacture of measuring testing instruments, clocks and watches", "C", "2.1"),
    "2651": ("Manufacture of instruments and appliances for measuring, testing and navigation", "C", "2.1"),
    "2652": ("Manufacture of watches and clocks", "C", "2.1"),
    "266": ("Manufacture of irradiation, electromedical and electrotherapeutic equipment", "C", "2.1"),
    "2660": ("Manufacture of irradiation, electromedical and electrotherapeutic equipment", "C", "2.1"),
    "267": ("Manufacture of optical instruments, magnetic and optical media and photographic equipment", "C", "2.1"),
    "2670": ("Manufacture of optical instruments, magnetic and optical media and photographic equipment", "C", "2.1"),
    "27": ("Manufacture of electrical equipment", "C", "2.1"),
    "271": ("Manufacture of electric motors, generators, transformers and electricity distribution and control apparatus", "C", "2.1"),
    "2711": ("Manufacture of electric motors, generators and transformers", "C", "2.1"),
    "2712": ("Manufacture of electricity distribution and control apparatus", "C", "2.1"),
    "272": ("Manufacture of batteries and accumulators", "C", "2.1"),
    "2720": ("Manufacture of batteries and accumulators", "C", "2.1"),
    "273": ("Manufacture of wiring and wiring devices", "C", "2.1"),
    "2731": ("Manufacture of fibre optic cables", "C", "2.1"),
    "2732": ("Manufacture of other electronic and electric wires and cables", "C", "2.1"),
    "2733": ("Manufacture of wiring devices", "C", "2.1"),
    "274": ("Manufacture of lighting equipment", "C", "2.1"),
    "2740": ("Manufacture of lighting equipment", "C", "2.1"),
    "275": ("Manufacture of domestic appliances", "C", "2.1"),
    "2751": ("Manufacture of electric domestic appliances", "C", "2.1"),
    "2752": ("Manufacture of non-electric domestic appliances", "C", "2.1"),
    "279": ("Manufacture of other electrical equipment", "C", "2.1"),
    "2790": ("Manufacture of other electrical equipment", "C", "2.1"),
    "28": ("Manufacture of machinery and equipment n.e.c.", "C", "2.1"),
    "281": ("Manufacture of general-purpose machinery", "C", "2.1"),
    "2811": ("Manufacture of engines and turbines, except aircraft, vehicle and cycle engines", "C", "2.1"),
    "2812": ("Manufacture of fluid power equipment", "C", "2.1"),
    "2813": ("Manufacture of other pumps and compressors", "C", "2.1"),
    "2814": ("Manufacture of other taps and valves", "C", "2.1"),
    "2815": ("Manufacture of bearings, gears, gearing and driving elements", "C", "2.1"),
    "282": ("Manufacture of other general-purpose machinery", "C", "2.1"),
    "2821": ("Manufacture of ovens, furnaces and permanent household heating equipment", "C", "2.1"),
    "2822": ("Manufacture of lifting and handling equipment", "C", "2.1"),
    "2823": ("Manufacture of office machinery and equipment, except computers and peripheral equipment", "C", "2.1"),
    "2824": ("Manufacture of power-driven hand tools", "C", "2.1"),
    "2825": ("Manufacture of non-domestic air conditioning equipment", "C", "2.1"),
    "2829": ("Manufacture of other general-purpose machinery n.e.c.", "C", "2.1"),
    "283": ("Manufacture of agricultural and forestry machinery", "C", "2.1"),
    "2830": ("Manufacture of agricultural and forestry machinery", "C", "2.1"),
    "284": ("Manufacture of metal forming machinery and machine tools", "C", "2.1"),
    "2841": ("Manufacture of metal forming machinery and machine tools for metal work", "C", "2.1"),
    "2842": ("Manufacture of other machine tools", "C", "2.1"),
    "289": ("Manufacture of other special-purpose machinery", "C", "2.1"),
    "2891": ("Manufacture of machinery for metallurgy", "C", "2.1"),
    "2892": ("Manufacture of machinery for mining, quarrying and construction", "C", "2.1"),
    "2893": ("Manufacture of machinery for food, beverage and tobacco processing", "C", "2.1"),
    "2894": ("Manufacture of machinery for textile, apparel and leather production", "C", "2.1"),
    "2895": ("Manufacture of machinery for paper and paperboard production", "C", "2.1"),
    "2896": ("Manufacture of plastics and rubber machinery", "C", "2.1"),
    "2897": ("Manufacture of additive manufacturing machinery", "C", "2.1"),
    "2899": ("Manufacture of other special-purpose machinery n.e.c.", "C", "2.1"),
    "29": ("Manufacture of motor vehicles, trailers and semi-trailers", "C", "2.1"),
    "291": ("Manufacture of motor vehicles", "C", "2.1"),
    "2910": ("Manufacture of motor vehicles", "C", "2.1"),
    "292": ("Manufacture of bodies and coachwork for motor vehicles; manufacture of trailers and semi-trailers", "C", "2.1"),
    "2920": ("Manufacture of bodies and coachwork for motor vehicles; manufacture of trailers and semi-trailers", "C", "2.1"),
    "293": ("Manufacture of motor vehicle parts and accessories", "C", "2.1"),
    "2931": ("Manufacture of electrical and electronic equipment for motor vehicles", "C", "2.1"),
    "2932": ("Manufacture of other parts and accessories for motor vehicles", "C", "2.1"),
    "30": ("Manufacture of other transport equipment", "C", "2.1"),
    "301": ("Building of ships and boats", "C", "2.1"),
    "3011": ("Building of civilian ships and floating structures", "C", "2.1"),
    "3012": ("Building of pleasure and sporting boats", "C", "2.1"),
    "3013": ("Building of military ships and vessels", "C", "2.1"),
    "302": ("Manufacture of railway locomotives and rolling stock", "C", "2.1"),
    "3020": ("Manufacture of railway locomotives and rolling stock", "C", "2.1"),
    "303": ("Manufacture of air and spacecraft and related machinery", "C", "2.1"),
    "3031": ("Manufacture of civilian air and spacecraft and related machinery", "C", "2.1"),
    "3032": ("Manufacture of military air and spacecraft and related machinery", "C", "2.1"),
    "304": ("Manufacture of military fighting vehicles", "C", "2.1"),
    "3040": ("Manufacture of military fighting vehicles", "C", "2.1"),
    "309": ("Manufacture of transport equipment n.e.c.", "C", "2.1"),
    "3091": ("Manufacture of motorcycles", "C", "2.1"),
    "3092": ("Manufacture of bicycles and invalid carriages", "C", "2.1"),
    "3099": ("Manufacture of other transport equipment n.e.c.", "C", "2.1"),
    "31": ("Manufacture of furniture", "C", "2.1"),
    "310": ("Manufacture of furniture", "C", "2.1"),
    "3100": ("Manufacture of furniture", "C", "2.1"),
    "32": ("Other manufacturing", "C", "2.1"),
    "321": ("Manufacture of jewellery, bijouterie and related articles", "C", "2.1"),
    "3211": ("Striking of coins", "C", "2.1"),
    "3212": ("Manufacture of jewellery and related articles", "C", "2.1"),
    "3213": ("Manufacture of imitation jewellery and related articles", "C", "2.1"),
    "322": ("Manufacture of musical instruments", "C", "2.1"),
    "3220": ("Manufacture of musical instruments", "C", "2.1"),
    "323": ("Manufacture of sports goods", "C", "2.1"),
    "3230": ("Manufacture of sports goods", "C", "2.1"),
    "324": ("Manufacture of games and toys", "C", "2.1"),
    "3240": ("Manufacture of games and toys", "C", "2.1"),
    "325": ("Manufacture of medical and dental instruments and supplies", "C", "2.1"),
    "3250": ("Manufacture of medical and dental instruments and supplies", "C", "2.1"),
    "329": ("Manufacturing n.e.c.", "C", "2.1"),
    "3291": ("Manufacture of brooms and brushes", "C", "2.1"),
    "3299": ("Other manufacturing n.e.c.", "C", "2.1"),
    "33": ("Repair, maintenance and installation of machinery and equipment", "C", "2.1"),
    "331": ("Repair and maintenance of fabricated metal products, machinery and equipment", "C", "2.1"),
    "3311": ("Repair and maintenance of fabricated metal products", "C", "2.1"),
    "3312": ("Repair and maintenance of machinery", "C", "2.1"),
    "3313": ("Repair and maintenance of electronic and optical equipment", "C", "2.1"),
    "3314": ("Repair and maintenance of electrical equipment", "C", "2.1"),
    "3315": ("Repair and maintenance of civilian ships and boats", "C", "2.1"),
    "3316": ("Repair and maintenance of civilian air and spacecraft", "C", "2.1"),
    "3317": ("Repair and maintenance of other civilian transport equipment", "C", "2.1"),
    "3318": ("Repair and maintenance of military fighting vehicles, ships, boats, air and spacecraft", "C", "2.1"),
    "3319": ("Repair and maintenance of other equipment", "C", "2.1"),
    "332": ("Installation of industrial machinery and equipment", "C", "2.1"),
    "3320": ("Installation of industrial machinery and equipment", "C", "2.1"),
    "35": ("Electricity, gas, steam and air conditioning supply", "D", "2.1"),
    "351": ("Electric power generation, transmission and distribution", "D", "2.1"),
    "3511": ("Production of electricity from non-renewable sources", "D", "2.1"),
    "3512": ("Production of electricity from renewable sources", "D", "2.1"),
    "3513": ("Transmission of electricity", "D", "2.1"),
    "3514": ("Distribution of electricity", "D", "2.1"),
    "3515": ("Trade of electricity", "D", "2.1"),
    "3516": ("Storage of electricity", "D", "2.1"),
    "352": ("Manufacture of gas, and distribution of gaseous fuels through mains", "D", "2.1"),
    "3521": ("Manufacture of gas", "D", "2.1"),
    "3522": ("Distribution of gaseous fuels through mains", "D", "2.1"),
    "3523": ("Trade of gas through mains", "D", "2.1"),
    "3524": ("Storage of gas as part of network supply services", "D", "2.1"),
    "353": ("Steam and air conditioning supply", "D", "2.1"),
    "3530": ("Steam and air conditioning supply", "D", "2.1"),
    "354": ("Activities of brokers and agents for electric power and natural gas", "D", "2.1"),
    "3540": ("Activities of brokers and agents for electric power and natural gas", "D", "2.1"),
    "36": ("Water collection, treatment and supply", "E", "2.1"),
    "360": ("Water collection, treatment and supply", "E", "2.1"),
    "3600": ("Water collection, treatment and supply", "E", "2.1"),
    "37": ("Sewerage", "E", "2.1"),
    "370": ("Sewerage", "E", "2.1"),
    "3700": ("Sewerage", "E", "2.1"),
    "38": ("Waste collection, recovery and disposal activities", "E", "2.1"),
    "381": ("Waste collection", "E", "2.1"),
    "3811": ("Collection of non-hazardous waste", "E", "2.1"),
    "3812": ("Collection of hazardous waste", "E", "2.1"),
    "382": ("Waste recovery", "E", "2.1"),
    "3821": ("Materials recovery", "E", "2.1"),
    "3822": ("Energy recovery", "E", "2.1"),
    "3823": ("Other waste recovery", "E", "2.1"),
    "383": ("Waste disposal without recovery", "E", "2.1"),
    "3831": ("Incineration without energy recovery", "E", "2.1"),
    "3832": ("Landfilling or permanent storage", "E", "2.1"),
    "3833": ("Other waste disposal", "E", "2.1"),
    "39": ("Remediation activities and other waste management service activities", "E", "2.1"),
    "390": ("Remediation activities and other waste management service activities", "E", "2.1"),
    "3900": ("Remediation activities and other waste management service activities", "E", "2.1"),
    "41": ("Construction of residential and non-residential buildings", "F", "2.1"),
    "410": ("Construction of residential and non-residential buildings", "F", "2.1"),
    "4100": ("Construction of residential and non-residential buildings", "F", "2.1"),
    "42": ("Civil engineering", "F", "2.1"),
    "421": ("Construction of roads and railways", "F", "2.1"),
    "4211": ("Construction of roads and motorways", "F", "2.1"),
    "4212": ("Construction of railways and underground railways", "F", "2.1"),
    "4213": ("Construction of bridges and tunnels", "F", "2.1"),
    "422": ("Construction of utility projects", "F", "2.1"),
    "4221": ("Construction of utility projects for fluids", "F", "2.1"),
    "4222": ("Construction of utility projects for electricity and telecommunications", "F", "2.1"),
    "429": ("Construction of other civil engineering projects", "F", "2.1"),
    "4291": ("Construction of water projects", "F", "2.1"),
    "4299": ("Construction of other civil engineering projects n.e.c.", "F", "2.1"),
    "43": ("Specialised construction activities", "F", "2.1"),
    "431": ("Demolition and site preparation", "F", "2.1"),
    "4311": ("Demolition", "F", "2.1"),
    "4312": ("Site preparation", "F", "2.1"),
    "4313": ("Test drilling and boring", "F", "2.1"),
    "432": ("Electrical, plumbing and other construction installation activities", "F", "2.1"),
    "4321": ("Electrical installation", "F", "2.1"),
    "4322": ("Plumbing, heat and air-conditioning installation", "F", "2.1"),
    "4323": ("Installation of insulation", "F", "2.1"),
    "4324": ("Other construction installation", "F", "2.1"),
    "433": ("Building completion and finishing", "F", "2.1"),
    "4331": ("Plastering", "F", "2.1"),
    "4332": ("Joinery installation", "F", "2.1"),
    "4333": ("Floor and wall covering", "F", "2.1"),
    "4334": ("Painting and glazing", "F", "2.1"),
    "4335": ("Other building completion and finishing", "F", "2.1"),
    "434": ("Specialised construction activities in construction of buildings", "F", "2.1"),
    "4341": ("Roofing activities", "F", "2.1"),
    "4342": ("Other specialised construction activities in construction of buildings", "F", "2.1"),
    "435": ("Specialised construction activities in civil engineering", "F", "2.1"),
    "4350": ("Specialised construction activities in civil engineering", "F", "2.1"),
    "436": ("Intermediation service activities for specialised construction services", "F", "2.1"),
    "4360": ("Intermediation service activities for specialised construction services", "F", "2.1"),
    "439": ("Other specialised construction activities", "F", "2.1"),
    "4391": ("Masonry and bricklaying activities", "F", "2.1"),
    "4399": ("Other specialised construction activities n.e.c.", "F", "2.1"),
    "46": ("Wholesale trade", "G", "2.1"),
    "461": ("Wholesale on a fee or contract basis", "G", "2.1"),
    "4611": ("Activities of agents involved in the wholesale of agricultural raw materials, live animals, textile raw materials and semi-finished goods", "G", "2.1"),
    "4612": ("Activities of agents involved in the wholesale of fuels, ores, metals and industrial chemicals", "G", "2.1"),
    "4613": ("Activities of agents involved in the wholesale of timber and building materials", "G", "2.1"),
    "4614": ("Activities of agents involved in the wholesale of machinery, industrial equipment, ships and aircraft", "G", "2.1"),
    "4615": ("Activities of agents involved in the wholesale of furniture, household goods, hardware and ironmongery", "G", "2.1"),
    "4616": ("Activities of agents involved in the wholesale of textiles, clothing, fur, footwear and leather goods", "G", "2.1"),
    "4617": ("Activities of agents involved in the wholesale of food, beverages and tobacco", "G", "2.1"),
    "4618": ("Activities of agents involved in the wholesale of other particular products", "G", "2.1"),
    "4619": ("Activities of agents involved in non-specialised wholesale", "G", "2.1"),
    "462": ("Wholesale of agricultural raw materials and live animals", "G", "2.1"),
    "4621": ("Wholesale of grain, unmanufactured tobacco, seeds and animal feeds", "G", "2.1"),
    "4622": ("Wholesale of flowers and plants", "G", "2.1"),
    "4623": ("Wholesale of live animals", "G", "2.1"),
    "4624": ("Wholesale of hides, skins and leather", "G", "2.1"),
    "463": ("Wholesale of food, beverages and tobacco", "G", "2.1"),
    "4631": ("Wholesale of fruit and vegetables", "G", "2.1"),
    "4632": ("Wholesale of meat, meat products, fish and fish products", "G", "2.1"),
    "4633": ("Wholesale of dairy products, eggs and edible oils and fats", "G", "2.1"),
    "4634": ("Wholesale of beverages", "G", "2.1"),
    "4635": ("Wholesale of tobacco products", "G", "2.1"),
    "4636": ("Wholesale of sugar, chocolate and sugar confectionery", "G", "2.1"),
    "4637": ("Wholesale of coffee, tea, cocoa and spices", "G", "2.1"),
    "4638": ("Wholesale of other food", "G", "2.1"),
    "4639": ("Non-specialised wholesale of food, beverages and tobacco", "G", "2.1"),
    "464": ("Wholesale of household goods", "G", "2.1"),
    "4641": ("Wholesale of textiles", "G", "2.1"),
    "4642": ("Wholesale of clothing and footwear", "G", "2.1"),
    "4643": ("Wholesale of electrical household appliances", "G", "2.1"),
    "4644": ("Wholesale of china and glassware and cleaning materials", "G", "2.1"),
    "4645": ("Wholesale of perfume and cosmetics", "G", "2.1"),
    "4646": ("Wholesale of pharmaceutical and medical goods", "G", "2.1"),
    "4647": ("Wholesale of household, office and shop furniture, carpets and lighting equipment", "G", "2.1"),
    "4648": ("Wholesale of watches and jewellery", "G", "2.1"),
    "4649": ("Wholesale of other household goods", "G", "2.1"),
    "465": ("Wholesale of information and communication equipment", "G", "2.1"),
    "4650": ("Wholesale of information and communication equipment", "G", "2.1"),
    "466": ("Wholesale of other machinery, equipment and supplies", "G", "2.1"),
    "4661": ("Wholesale of agricultural machinery, equipment and supplies", "G", "2.1"),
    "4662": ("Wholesale of machine tools", "G", "2.1"),
    "4663": ("Wholesale of mining, construction and civil engineering machinery", "G", "2.1"),
    "4664": ("Wholesale of other machinery and equipment", "G", "2.1"),
    "467": ("Wholesale of motor vehicles, motorcycles and related parts and accessories", "G", "2.1"),
    "4671": ("Wholesale of motor vehicles", "G", "2.1"),
    "4672": ("Wholesale of motor vehicle parts and accessories", "G", "2.1"),
    "4673": ("Wholesale of motorcycles, motorcycle parts and accessories", "G", "2.1"),
    "468": ("Other specialised wholesale", "G", "2.1"),
    "4681": ("Wholesale of solid, liquid and gaseous fuels and related products", "G", "2.1"),
    "4682": ("Wholesale of metals and metal ores", "G", "2.1"),
    "4683": ("Wholesale of wood, construction materials and sanitary equipment", "G", "2.1"),
    "4684": ("Wholesale of hardware, plumbing and heating equipment and supplies", "G", "2.1"),
    "4685": ("Wholesale of chemical products", "G", "2.1"),
    "4686": ("Wholesale of other intermediate products", "G", "2.1"),
    "4687": ("Wholesale of waste and scrap", "G", "2.1"),
    "4689": ("Other specialised wholesale n.e.c.", "G", "2.1"),
    "469": ("Non-specialised wholesale trade", "G", "2.1"),
    "4690": ("Non-specialised wholesale trade", "G", "2.1"),
    "47": ("Retail trade", "G", "2.1"),
    "471": ("Non-specialised retail sale", "G", "2.1"),
    "4711": ("Non-specialised retail sale of predominately food, beverages or tobacco", "G", "2.1"),
    "4712": ("Other non-specialised retail sale", "G", "2.1"),
    "472": ("Retail sale of food, beverages and tobacco", "G", "2.1"),
    "4721": ("Retail sale of fruit and vegetables", "G", "2.1"),
    "4722": ("Retail sale of meat and meat products", "G", "2.1"),
    "4723": ("Retail sale of fish, crustaceans and molluscs", "G", "2.1"),
    "4724": ("Retail sale of bread, cake and confectionery", "G", "2.1"),
    "4725": ("Retail sale of beverages", "G", "2.1"),
    "4726": ("Retail sale of tobacco products", "G", "2.1"),
    "4727": ("Retail sale of other food", "G", "2.1"),
    "473": ("Retail sale of automotive fuel", "G", "2.1"),
    "4730": ("Retail sale of automotive fuel", "G", "2.1"),
    "474": ("Retail sale of information and communication equipment", "G", "2.1"),
    "4740": ("Retail sale of information and communication equipment", "G", "2.1"),
    "475": ("Retail sale of other household equipment", "G", "2.1"),
    "4751": ("Retail sale of textiles", "G", "2.1"),
    "4752": ("Retail sale of hardware, building materials, paints and glass", "G", "2.1"),
    "4753": ("Retail sale of carpets, rugs, wall and floor coverings", "G", "2.1"),
    "4754": ("Retail sale of electrical household appliances", "G", "2.1"),
    "4755": ("Retail sale of furniture, lighting equipment, tableware and other household goods", "G", "2.1"),
    "476": ("Retail sale of cultural and recreational goods", "G", "2.1"),
    "4761": ("Retail sale of books", "G", "2.1"),
    "4762": ("Retail sale of newspapers, and other periodical publications and stationery", "G", "2.1"),
    "4763": ("Retail sale of sporting equipment", "G", "2.1"),
    "4764": ("Retail sale of games and toys", "G", "2.1"),
    "4769": ("Retail sale of cultural and recreational goods n.e.c.", "G", "2.1"),
    "477": ("Retail sale of other goods, except motor vehicles and motorcycles", "G", "2.1"),
    "4771": ("Retail sale of clothing", "G", "2.1"),
    "4772": ("Retail sale of footwear and leather goods", "G", "2.1"),
    "4773": ("Retail sale of pharmaceutical products", "G", "2.1"),
    "4774": ("Retail sale of medical and orthopaedic goods", "G", "2.1"),
    "4775": ("Retail sale of cosmetic and toilet articles", "G", "2.1"),
    "4776": ("Retail sale of flowers, plants, fertilisers, pets and pet food", "G", "2.1"),
    "4777": ("Retail sale of watches and jewellery", "G", "2.1"),
    "4778": ("Retail sale of other new goods", "G", "2.1"),
    "4779": ("Retail sale of second-hand goods", "G", "2.1"),
    "478": ("Retail sale of motor vehicles, motorcycles and related parts and accessories", "G", "2.1"),
    "4781": ("Retail sale of motor vehicles", "G", "2.1"),
    "4782": ("Retail sale of motor vehicle parts and accessories", "G", "2.1"),
    "4783": ("Retail sale of motorcycles, motorcycle parts and accessories", "G", "2.1"),
    "479": ("Intermediation service activities for retail sale", "G", "2.1"),
    "4791": ("Intermediation service activities for non-specialised retail sale", "G", "2.1"),
    "4792": ("Intermediation service activities for specialised retail sale", "G", "2.1"),
    "49": ("Land transport and transport via pipelines", "H", "2.1"),
    "491": ("Passenger rail transport", "H", "2.1"),
    "4911": ("Passenger heavy rail transport", "H", "2.1"),
    "4912": ("Other passenger rail transport", "H", "2.1"),
    "492": ("Freight rail transport", "H", "2.1"),
    "4920": ("Freight rail transport", "H", "2.1"),
    "493": ("Other passenger land transport", "H", "2.1"),
    "4931": ("Scheduled passenger transport by road", "H", "2.1"),
    "4932": ("Non-scheduled passenger transport by road", "H", "2.1"),
    "4933": ("On-demand passenger transport service activities by vehicle with driver", "H", "2.1"),
    "4934": ("Passenger transport by cableways and ski lifts", "H", "2.1"),
    "4939": ("Other passenger land transport n.e.c.", "H", "2.1"),
    "494": ("Freight transport by road and removal services", "H", "2.1"),
    "4941": ("Freight transport by road", "H", "2.1"),
    "4942": ("Removal services", "H", "2.1"),
    "495": ("Transport via pipeline", "H", "2.1"),
    "4950": ("Transport via pipeline", "H", "2.1"),
    "50": ("Water transport", "H", "2.1"),
    "501": ("Sea and coastal passenger water transport", "H", "2.1"),
    "5010": ("Sea and coastal passenger water transport", "H", "2.1"),
    "502": ("Sea and coastal freight water transport", "H", "2.1"),
    "5020": ("Sea and coastal freight water transport", "H", "2.1"),
    "503": ("Inland passenger water transport", "H", "2.1"),
    "5030": ("Inland passenger water transport", "H", "2.1"),
    "504": ("Inland freight water transport", "H", "2.1"),
    "5040": ("Inland freight water transport", "H", "2.1"),
    "51": ("Air transport", "H", "2.1"),
    "511": ("Passenger air transport", "H", "2.1"),
    "5110": ("Passenger air transport", "H", "2.1"),
    "512": ("Freight air transport and space transport", "H", "2.1"),
    "5121": ("Freight air transport", "H", "2.1"),
    "5122": ("Space transport", "H", "2.1"),
    "52": ("Warehousing, storage and support activities for transportation", "H", "2.1"),
    "521": ("Warehousing and storage", "H", "2.1"),
    "5210": ("Warehousing and storage", "H", "2.1"),
    "522": ("Support activities for transportation", "H", "2.1"),
    "5221": ("Service activities incidental to land transportation", "H", "2.1"),
    "5222": ("Service activities incidental to water transportation", "H", "2.1"),
    "5223": ("Service activities incidental to air transportation", "H", "2.1"),
    "5224": ("Cargo handling", "H", "2.1"),
    "5225": ("Logistics service activities", "H", "2.1"),
    "5226": ("Other support activities for transportation", "H", "2.1"),
    "523": ("Intermediation service activities for transportation", "H", "2.1"),
    "5231": ("Intermediation service activities for freight transportation", "H", "2.1"),
    "5232": ("Intermediation service activities for passenger transportation", "H", "2.1"),
    "53": ("Postal and courier activities", "H", "2.1"),
    "531": ("Postal activities under universal service obligation", "H", "2.1"),
    "5310": ("Postal activities under universal service obligation", "H", "2.1"),
    "532": ("Other postal and courier activities", "H", "2.1"),
    "5320": ("Other postal and courier activities", "H", "2.1"),
    "533": ("Intermediation service activities for postal and courier activities", "H", "2.1"),
    "5330": ("Intermediation service activities for postal and courier activities", "H", "2.1"),
    "55": ("Accommodation", "I", "2.1"),
    "551": ("Hotels and similar accommodation", "I", "2.1"),
    "5510": ("Hotels and similar accommodation", "I", "2.1"),
    "552": ("Holiday and other short-stay accommodation", "I", "2.1"),
    "5520": ("Holiday and other short-stay accommodation", "I", "2.1"),
    "553": ("Camping grounds and recreational vehicle parks", "I", "2.1"),
    "5530": ("Camping grounds and recreational vehicle parks", "I", "2.1"),
    "554": ("Intermediation service activities for accommodation", "I", "2.1"),
    "5540": ("Intermediation service activities for accommodation", "I", "2.1"),
    "559": ("Other accommodation", "I", "2.1"),
    "5590": ("Other accommodation", "I", "2.1"),
    "56": ("Food and beverage service activities", "I", "2.1"),
    "561": ("Restaurants and mobile food service activities", "I", "2.1"),
    "5611": ("Restaurant activities", "I", "2.1"),
    "5612": ("Mobile food service activities", "I", "2.1"),
    "562": ("Event catering, contract catering service activities and other food service activities", "I", "2.1"),
    "5621": ("Event catering activities", "I", "2.1"),
    "5622": ("Contract catering service activities and other food service activities", "I", "2.1"),
    "563": ("Beverage serving activities", "I", "2.1"),
    "5630": ("Beverage serving activities", "I", "2.1"),
    "564": ("Intermediation service activities for food and beverage services activities", "I", "2.1"),
    "5640": ("Intermediation service activities for food and beverage services activities", "I", "2.1"),
    "58": ("Publishing activities", "J", "2.1"),
    "581": ("Publishing of books, newspapers and other publishing activities, except software publishing", "J", "2.1"),
    "5811": ("Publishing of books", "J", "2.1"),
    "5812": ("Publishing of newspapers", "J", "2.1"),
    "5813": ("Publishing of journals and periodicals", "J", "2.1"),
    "5819": ("Other publishing activities, except software publishing", "J", "2.1"),
    "582": ("Software publishing", "J", "2.1"),
    "5821": ("Publishing of video games", "J", "2.1"),
    "5829": ("Other software publishing", "J", "2.1"),
    "59": ("Motion picture, video and television programme production, sound recording and music publishing activities", "J", "2.1"),
    "591": ("Motion picture, video and television programme activities", "J", "2.1"),
    "5911": ("Motion picture, video and television programme production activities", "J", "2.1"),
    "5912": ("Motion picture, video and television programme post-production activities", "J", "2.1"),
    "5913": ("Motion picture and video distribution activities", "J", "2.1"),
    "5914": ("Motion picture projection activities", "J", "2.1"),
    "592": ("Sound recording and music publishing activities", "J", "2.1"),
    "5920": ("Sound recording and music publishing activities", "J", "2.1"),
    "60": ("Programming, broadcasting, news agency and other content distribution activities", "J", "2.1"),
    "601": ("Radio broadcasting and audio distribution activities", "J", "2.1"),
    "6010": ("Radio broadcasting and audio distribution activities", "J", "2.1"),
    "602": ("Television programming, broadcasting and video distribution activities", "J", "2.1"),
    "6020": ("Television programming, broadcasting and video distribution activities", "J", "2.1"),
    "603": ("News agency and other content distribution activities", "J", "2.1"),
    "6031": ("News agency activities", "J", "2.1"),
    "6039": ("Other content distribution activities", "J", "2.1"),
    "61": ("Telecommunication", "K", "2.1"),
    "611": ("Wired, wireless, and satellite telecommunication activities", "K", "2.1"),
    "6110": ("Wired, wireless, and satellite telecommunication activities", "K", "2.1"),
    "612": ("Telecommunication reselling activities and intermediation service activities for telecommunication", "K", "2.1"),
    "6120": ("Telecommunication reselling activities and intermediation service activities for telecommunication", "K", "2.1"),
    "619": ("Other telecommunications activities", "K", "2.1"),
    "6190": ("Other telecommunications activities", "K", "2.1"),
    "62": ("Computer programming, consultancy and related activities", "K", "2.1"),
    "621": ("Computer programming activities", "K", "2.1"),
    "6210": ("Computer programming activities", "K", "2.1"),
    "622": ("Computer consultancy and computer facilities management activities", "K", "2.1"),
    "6220": ("Computer consultancy and computer facilities management activities", "K", "2.1"),
    "629": ("Other information technology and computer service activities", "K", "2.1"),
    "6290": ("Other information technology and computer service activities", "K", "2.1"),
    "63": ("Computing infrastructure, data processing, hosting and other information service activities", "K", "2.1"),
    "631": ("Computing infrastructure, data processing, hosting and related activities", "K", "2.1"),
    "6310": ("Computing infrastructure, data processing, hosting and related activities", "K", "2.1"),
    "639": ("Web search portal activities and other information service activities", "K", "2.1"),
    "6391": ("Web search portal activities", "K", "2.1"),
    "6392": ("Other information service activities", "K", "2.1"),
    "64": ("Financial service activities, except insurance and pension funding", "L", "2.1"),
    "641": ("Monetary intermediation", "L", "2.1"),
    "6411": ("Central banking", "L", "2.1"),
    "6419": ("Other monetary intermediation", "L", "2.1"),
    "642": ("Activities of holding companies and financing conduits", "L", "2.1"),
    "6421": ("Activities of holding companies", "L", "2.1"),
    "6422": ("Activities of financing conduits", "L", "2.1"),
    "643": ("Activities of trusts, funds and similar financial entities", "L", "2.1"),
    "6431": ("Activities of money market and non-money market investments funds", "L", "2.1"),
    "6432": ("Activities of trust, estate and agency accounts", "L", "2.1"),
    "649": ("Other financial service activities, except insurance and pension funding", "L", "2.1"),
    "6491": ("Financial leasing", "L", "2.1"),
    "6492": ("Other credit granting", "L", "2.1"),
    "6499": ("Other financial service activities, except insurance and pension funding n.e.c.", "L", "2.1"),
    "65": ("Insurance, reinsurance and pension funding, except compulsory social security", "L", "2.1"),
    "651": ("Insurance", "L", "2.1"),
    "6511": ("Life insurance", "L", "2.1"),
    "6512": ("Non-life insurance", "L", "2.1"),
    "652": ("Reinsurance", "L", "2.1"),
    "6520": ("Reinsurance", "L", "2.1"),
    "653": ("Pension funding", "L", "2.1"),
    "6530": ("Pension funding", "L", "2.1"),
    "66": ("Activities auxiliary to financial services and insurance activities", "L", "2.1"),
    "661": ("Activities auxiliary to financial services, except insurance and pension funding", "L", "2.1"),
    "6611": ("Administration of financial markets", "L", "2.1"),
    "6612": ("Security and commodity contracts brokerage", "L", "2.1"),
    "6619": ("Other activities auxiliary to financial services, except insurance and pension funding", "L", "2.1"),
    "662": ("Activities auxiliary to insurance and pension funding", "L", "2.1"),
    "6621": ("Risk and damage evaluation", "L", "2.1"),
    "6622": ("Activities of insurance agents and brokers", "L", "2.1"),
    "6629": ("Activities auxiliary to insurance and pension funding n.e.c.", "L", "2.1"),
    "663": ("Fund management activities", "L", "2.1"),
    "6630": ("Fund management activities", "L", "2.1"),
    "68": ("Real estate activities", "M", "2.1"),
    "681": ("Real estate activities with own property and development of building projects", "M", "2.1"),
    "6811": ("Buying and selling of own real estate", "M", "2.1"),
    "6812": ("Development of building projects", "M", "2.1"),
    "682": ("Rental and operating of own or leased real estate", "M", "2.1"),
    "6820": ("Rental and operating of own or leased real estate", "M", "2.1"),
    "683": ("Real estate activities on a fee or contract basis", "M", "2.1"),
    "6831": ("Intermediation service activities for real estate activities", "M", "2.1"),
    "6832": ("Other real estate activities on a fee or contract basis", "M", "2.1"),
    "69": ("Legal and accounting activities", "N", "2.1"),
    "691": ("Legal activities", "N", "2.1"),
    "6910": ("Legal activities", "N", "2.1"),
    "692": ("Accounting, bookkeeping and auditing activities; tax consultancy", "N", "2.1"),
    "6920": ("Accounting, bookkeeping and auditing activities; tax consultancy", "N", "2.1"),
    "70": ("Activities of head offices and management consultancy", "N", "2.1"),
    "701": ("Activities of head offices", "N", "2.1"),
    "7010": ("Activities of head offices", "N", "2.1"),
    "702": ("Business and other management consultancy activities", "N", "2.1"),
    "7020": ("Business and other management consultancy activities", "N", "2.1"),
    "71": ("Architectural and engineering activities; technical testing and analysis", "N", "2.1"),
    "711": ("Architectural and engineering activities and related technical consultancy", "N", "2.1"),
    "7111": ("Architectural activities", "N", "2.1"),
    "7112": ("Engineering activities and related technical consultancy", "N", "2.1"),
    "712": ("Technical testing and analysis", "N", "2.1"),
    "7120": ("Technical testing and analysis", "N", "2.1"),
    "72": ("Scientific research and development", "N", "2.1"),
    "721": ("Research and experimental development on natural sciences and engineering", "N", "2.1"),
    "7210": ("Research and experimental development on natural sciences and engineering", "N", "2.1"),
    "722": ("Research and experimental development on social sciences and humanities", "N", "2.1"),
    "7220": ("Research and experimental development on social sciences and humanities", "N", "2.1"),
    "73": ("Activities of advertising, market research and public relations", "N", "2.1"),
    "731": ("Advertising", "N", "2.1"),
    "7311": ("Activities of advertising agencies", "N", "2.1"),
    "7312": ("Media representation", "N", "2.1"),
    "732": ("Market research and public opinion polling", "N", "2.1"),
    "7320": ("Market research and public opinion polling", "N", "2.1"),
    "733": ("Public relations and communication activities", "N", "2.1"),
    "7330": ("Public relations and communication activities", "N", "2.1"),
    "74": ("Other professional, scientific and technical activities", "N", "2.1"),
    "741": ("Specialised design activities", "N", "2.1"),
    "7411": ("Industrial product and fashion design activities", "N", "2.1"),
    "7412": ("Graphic design and visual communication activities", "N", "2.1"),
    "7413": ("Interior design activities", "N", "2.1"),
    "7414": ("Other specialised design activities", "N", "2.1"),
    "742": ("Photographic activities", "N", "2.1"),
    "7420": ("Photographic activities", "N", "2.1"),
    "743": ("Translation and interpretation activities", "N", "2.1"),
    "7430": ("Translation and interpretation activities", "N", "2.1"),
    "749": ("Other professional, scientific and technical activities n.e.c.", "N", "2.1"),
    "7491": ("Patent brokering and marketing service activities", "N", "2.1"),
    "7499": ("All other professional, scientific and technical activities n.e.c.", "N", "2.1"),
    "75": ("Veterinary activities", "N", "2.1"),
    "750": ("Veterinary activities", "N", "2.1"),
    "7500": ("Veterinary activities", "N", "2.1"),
    "77": ("Rental and leasing activities", "O", "2.1"),
    "771": ("Rental and leasing of motor vehicles", "O", "2.1"),
    "7711": ("Rental and leasing of cars and light motor vehicles", "O", "2.1"),
    "7712": ("Rental and leasing of trucks", "O", "2.1"),
    "772": ("Rental and leasing of personal and household goods", "O", "2.1"),
    "7721": ("Rental and leasing of recreational and sports goods", "O", "2.1"),
    "7722": ("Rental and leasing of other personal and household goods", "O", "2.1"),
    "773": ("Rental and leasing of other machinery, equipment and tangible goods", "O", "2.1"),
    "7731": ("Rental and leasing of agricultural machinery and equipment", "O", "2.1"),
    "7732": ("Rental and leasing of construction and civil engineering machinery and equipment", "O", "2.1"),
    "7733": ("Rental and leasing of office machinery, equipment and computers", "O", "2.1"),
    "7734": ("Rental and leasing of water transport equipment", "O", "2.1"),
    "7735": ("Rental and leasing of air transport equipment", "O", "2.1"),
    "7739": ("Rental and leasing of other machinery, equipment and tangible goods n.e.c.", "O", "2.1"),
    "774": ("Leasing of intellectual property and similar products, except copyrighted works", "O", "2.1"),
    "7740": ("Leasing of intellectual property and similar products, except copyrighted works", "O", "2.1"),
    "775": ("Intermediation service activities for rental and leasing of tangible goods and non-financial intangible assets", "O", "2.1"),
    "7751": ("Intermediation service activities for rental and leasing of cars, motorhomes and trailers", "O", "2.1"),
    "7752": ("Intermediation service activities for rental and leasing of other tangible goods and non-financial intangible assets", "O", "2.1"),
    "78": ("Employment activities", "O", "2.1"),
    "781": ("Activities of employment placement agencies", "O", "2.1"),
    "7810": ("Activities of employment placement agencies", "O", "2.1"),
    "782": ("Temporary employment agency activities and other human resource provisions", "O", "2.1"),
    "7820": ("Temporary employment agency activities and other human resource provisions", "O", "2.1"),
    "79": ("Travel agency, tour operator and other reservation service and related activities", "O", "2.1"),
    "791": ("Travel agency and tour operator activities", "O", "2.1"),
    "7911": ("Travel agency activities", "O", "2.1"),
    "7912": ("Tour operator activities", "O", "2.1"),
    "799": ("Other reservation service and related activities", "O", "2.1"),
    "7990": ("Other reservation service and related activities", "O", "2.1"),
    "80": ("Investigation and security activities", "O", "2.1"),
    "800": ("Investigation and security activities", "O", "2.1"),
    "8001": ("Investigation and private security activities", "O", "2.1"),
    "8009": ("Security activities n.e.c.", "O", "2.1"),
    "81": ("Services to buildings and landscape activities", "O", "2.1"),
    "811": ("Combined facilities support activities", "O", "2.1"),
    "8110": ("Combined facilities support activities", "O", "2.1"),
    "812": ("Cleaning activities", "O", "2.1"),
    "8121": ("General cleaning of buildings", "O", "2.1"),
    "8122": ("Other building and industrial cleaning activities", "O", "2.1"),
    "8123": ("Other cleaning activities", "O", "2.1"),
    "813": ("Landscape service activities", "O", "2.1"),
    "8130": ("Landscape service activities", "O", "2.1"),
    "82": ("Office administrative, office support and other business support activities", "O", "2.1"),
    "821": ("Office administrative and support activities", "O", "2.1"),
    "8210": ("Office administrative and support activities", "O", "2.1"),
    "822": ("Activities of call centres", "O", "2.1"),
    "8220": ("Activities of call centres", "O", "2.1"),
    "823": ("Organisation of conventions and trade shows", "O", "2.1"),
    "8230": ("Organisation of conventions and trade shows", "O", "2.1"),
    "824": ("Intermediation service activities for business support service activities n.e.c.", "O", "2.1"),
    "8240": ("Intermediation service activities for business support service activities n.e.c.", "O", "2.1"),
    "829": ("Business support service activities n.e.c.", "O", "2.1"),
    "8291": ("Activities of collection agencies and credit bureaus", "O", "2.1"),
    "8292": ("Packaging activities", "O", "2.1"),
    "8299": ("Other business support service activities n.e.c.", "O", "2.1"),
    "84": ("Public administration and defence; compulsory social security", "P", "2.1"),
    "841": ("Administration of the State and the economic, social and environmental policies of the community", "P", "2.1"),
    "8411": ("General public administration activities", "P", "2.1"),
    "8412": ("Regulation of health care, education, cultural services and other social services", "P", "2.1"),
    "8413": ("Regulation of and contribution to more efficient operation of businesses", "P", "2.1"),
    "842": ("Provision of services to the community as a whole", "P", "2.1"),
    "8421": ("Foreign affairs", "P", "2.1"),
    "8422": ("Defence activities", "P", "2.1"),
    "8423": ("Justice and judicial activities", "P", "2.1"),
    "8424": ("Public order and safety activities", "P", "2.1"),
    "8425": ("Fire service activities", "P", "2.1"),
    "843": ("Compulsory social security activities", "P", "2.1"),
    "8430": ("Compulsory social security activities", "P", "2.1"),
    "85": ("Education", "Q", "2.1"),
    "851": ("Pre-primary education", "Q", "2.1"),
    "8510": ("Pre-primary education", "Q", "2.1"),
    "852": ("Primary education", "Q", "2.1"),
    "8520": ("Primary education", "Q", "2.1"),
    "853": ("Secondary and post-secondary non-tertiary education", "Q", "2.1"),
    "8531": ("General secondary education", "Q", "2.1"),
    "8532": ("Vocational secondary education", "Q", "2.1"),
    "8533": ("Post-secondary non-tertiary education", "Q", "2.1"),
    "854": ("Tertiary education", "Q", "2.1"),
    "8540": ("Tertiary education", "Q", "2.1"),
    "855": ("Other education", "Q", "2.1"),
    "8551": ("Sports and recreation education", "Q", "2.1"),
    "8552": ("Cultural education", "Q", "2.1"),
    "8553": ("Driving school activities", "Q", "2.1"),
    "8559": ("Other education n.e.c.", "Q", "2.1"),
    "856": ("Educational support activities", "Q", "2.1"),
    "8561": ("Intermediation service activities for courses and tutors", "Q", "2.1"),
    "8569": ("Educational support activities n.e.c.", "Q", "2.1"),
    "86": ("Human health activities", "R", "2.1"),
    "861": ("Hospital activities", "R", "2.1"),
    "8610": ("Hospital activities", "R", "2.1"),
    "862": ("Medical and dental practice activities", "R", "2.1"),
    "8621": ("General medical practice activities", "R", "2.1"),
    "8622": ("Medical specialists activities", "R", "2.1"),
    "8623": ("Dental practice care activities", "R", "2.1"),
    "869": ("Other human health activities", "R", "2.1"),
    "8691": ("Diagnostic imaging services and medical laboratory activities", "R", "2.1"),
    "8692": ("Patient transportation by ambulance", "R", "2.1"),
    "8693": ("Activities of psychologists and psychotherapists, except medical doctors", "R", "2.1"),
    "8694": ("Nursing and midwifery activities", "R", "2.1"),
    "8695": ("Physiotherapy activities", "R", "2.1"),
    "8696": ("Traditional, complementary and alternative medicine activities", "R", "2.1"),
    "8697": ("Intermediation service activities for medical, dental and other human health services", "R", "2.1"),
    "8699": ("Other human health activities n.e.c.", "R", "2.1"),
    "87": ("Residential care activities", "R", "2.1"),
    "871": ("Residential nursing care activities", "R", "2.1"),
    "8710": ("Residential nursing care activities", "R", "2.1"),
    "872": ("Residential care activities for persons living with or having a diagnosis of a mental illness or substance abuse", "R", "2.1"),
    "8720": ("Residential care activities for persons living with or having a diagnosis of a mental illness or substance abuse", "R", "2.1"),
    "873": ("Residential care activities for older persons or persons with physical disabilities", "R", "2.1"),
    "8730": ("Residential care activities for older persons or persons with physical disabilities", "R", "2.1"),
    "879": ("Other residential care activities", "R", "2.1"),
    "8791": ("Intermediation service activities for residential care activities", "R", "2.1"),
    "8799": ("Other residential care activities n.e.c.", "R", "2.1"),
    "88": ("Social work activities without accommodation", "R", "2.1"),
    "881": ("Social work activities without accommodation for older persons or persons with disabilities", "R", "2.1"),
    "8810": ("Social work activities without accommodation for older persons or persons with disabilities", "R", "2.1"),
    "889": ("Other social work activities without accommodation", "R", "2.1"),
    "8891": ("Child day-care activities", "R", "2.1"),
    "8899": ("Other social work activities without accommodation n.e.c.", "R", "2.1"),
    "90": ("Arts creation and performing arts activities", "S", "2.1"),
    "901": ("Arts creation activities", "S", "2.1"),
    "9011": ("Literary creation and musical composition activities", "S", "2.1"),
    "9012": ("Visual arts creation activities", "S", "2.1"),
    "9013": ("Other arts creation activities", "S", "2.1"),
    "902": ("Activities of performing arts", "S", "2.1"),
    "9020": ("Activities of performing arts", "S", "2.1"),
    "903": ("Support activities to arts creation and performing arts", "S", "2.1"),
    "9031": ("Operation of arts facilities and sites", "S", "2.1"),
    "9039": ("Other support activities to arts and performing arts", "S", "2.1"),
    "91": ("Libraries, archives, museums and other cultural activities", "S", "2.1"),
    "911": ("Library and archive activities", "S", "2.1"),
    "9111": ("Library activities", "S", "2.1"),
    "9112": ("Archive activities", "S", "2.1"),
    "912": ("Museum, collection, historical site and monument activities", "S", "2.1"),
    "9121": ("Museum and collection activities", "S", "2.1"),
    "9122": ("Historical site and monument activities", "S", "2.1"),
    "913": ("Conservation, restoration and other support activities for cultural heritage", "S", "2.1"),
    "9130": ("Conservation, restoration and other support activities for cultural heritage", "S", "2.1"),
    "914": ("Botanical and zoological garden and nature reserve activities", "S", "2.1"),
    "9141": ("Botanical and zoological garden activities", "S", "2.1"),
    "9142": ("Nature reserve activities", "S", "2.1"),
    "92": ("Gambling and betting activities", "S", "2.1"),
    "920": ("Gambling and betting activities", "S", "2.1"),
    "9200": ("Gambling and betting activities", "S", "2.1"),
    "93": ("Sports activities and amusement and recreation activities", "S", "2.1"),
    "931": ("Sports activities", "S", "2.1"),
    "9311": ("Operation of sports facilities", "S", "2.1"),
    "9312": ("Activities of sport clubs", "S", "2.1"),
    "9313": ("Activities of fitness centres", "S", "2.1"),
    "9319": ("Sports activities n.e.c.", "S", "2.1"),
    "932": ("Amusement and recreation activities", "S", "2.1"),
    "9321": ("Activities of amusement parks and theme parks", "S", "2.1"),
    "9329": ("Amusement and recreation activities n.e.c.", "S", "2.1"),
    "94": ("Activities of membership organisations", "T", "2.1"),
    "941": ("Activities of business, employers and professional membership organisations", "T", "2.1"),
    "9411": ("Activities of business and employers membership organisations", "T", "2.1"),
    "9412": ("Activities of professional membership organisations", "T", "2.1"),
    "942": ("Activities of trade unions", "T", "2.1"),
    "9420": ("Activities of trade unions", "T", "2.1"),
    "949": ("Activities of other membership organisations", "T", "2.1"),
    "9491": ("Activities of religious organisations", "T", "2.1"),
    "9492": ("Activities of political organisations", "T", "2.1"),
    "9499": ("Activities of other membership organisations n.e.c.", "T", "2.1"),
    "95": ("Repair and maintenance of computers, personal and household goods, and motor vehicles and motorcycles", "T", "2.1"),
    "951": ("Repair and maintenance of computers and communication equipment", "T", "2.1"),
    "9510": ("Repair and maintenance of computers and communication equipment", "T", "2.1"),
    "952": ("Repair and maintenance of personal and household goods", "T", "2.1"),
    "9521": ("Repair and maintenance of consumer electronics", "T", "2.1"),
    "9522": ("Repair and maintenance of household appliances and home and garden equipment", "T", "2.1"),
    "9523": ("Repair and maintenance of footwear and leather goods", "T", "2.1"),
    "9524": ("Repair and maintenance of furniture and home furnishings", "T", "2.1"),
    "9525": ("Repair and maintenance of watches, clocks and jewellery", "T", "2.1"),
    "9529": ("Repair and maintenance of personal and household goods n.e.c.", "T", "2.1"),
    "953": ("Repair and maintenance of motor vehicles and motorcycles", "T", "2.1"),
    "9531": ("Repair and maintenance of motor vehicles", "T", "2.1"),
    "9532": ("Repair and maintenance of motorcycles", "T", "2.1"),
    "954": ("Intermediation service activities for repair and maintenance of computers, personal and household goods, and motor vehicles and motorcycles", "T", "2.1"),
    "9540": ("Intermediation service activities for repair and maintenance of computers, personal and household goods, and motor vehicles and motorcycles", "T", "2.1"),
    "96": ("Personal service activities", "T", "2.1"),
    "961": ("Washing and cleaning of textile and fur products", "T", "2.1"),
    "9610": ("Washing and cleaning of textile and fur products", "T", "2.1"),
    "962": ("Hairdressing, beauty treatment, day spa and similar activities", "T", "2.1"),
    "9621": ("Hairdressing and barber activities", "T", "2.1"),
    "9622": ("Beauty care and other beauty treatment activities", "T", "2.1"),
    "9623": ("Day spa, sauna and steam bath activities", "T", "2.1"),
    "963": ("Funeral and related activities", "T", "2.1"),
    "9630": ("Funeral and related activities", "T", "2.1"),
    "964": ("Intermediation service activities for personal services", "T", "2.1"),
    "9640": ("Intermediation service activities for personal services", "T", "2.1"),
    "969": ("Other personal service activities", "T", "2.1"),
    "9691": ("Provision of domestic personal service activities", "T", "2.1"),
    "9699": ("Other personal service activities n.e.c.", "T", "2.1"),
    "97": ("Activities of households as employers of domestic personnel", "U", "2.1"),
    "970": ("Activities of households as employers of domestic personnel", "U", "2.1"),
    "9700": ("Activities of households as employers of domestic personnel", "U", "2.1"),
    "98": ("Undifferentiated goods- and service-producing activities of private households for own use", "U", "2.1"),
    "981": ("Undifferentiated goods-producing activities of private households for own use", "U", "2.1"),
    "9810": ("Undifferentiated goods-producing activities of private households for own use", "U", "2.1"),
    "982": ("Undifferentiated service-producing activities of private households for own use", "U", "2.1"),
    "9820": ("Undifferentiated service-producing activities of private households for own use", "U", "2.1"),

    # --- kody jen ze stare NACE Rev. 2 (CZ-NACE 2008) ---
    "0149": ("Raising of other animals", "A", "2"),
    "0164": ("Seed processing for propagation", "A", "2"),
    "1411": ("Manufacture of leather clothes", "C", "2"),
    "1412": ("Manufacture of workwear", "C", "2"),
    "1413": ("Manufacture of other outerwear", "C", "2"),
    "1414": ("Manufacture of underwear", "C", "2"),
    "1419": ("Manufacture of other wearing apparel and accessories", "C", "2"),
    "1420": ("Manufacture of articles of fur", "C", "2"),
    "143": ("Manufacture of knitted and crocheted apparel", "C", "2"),
    "1431": ("Manufacture of knitted and crocheted hosiery", "C", "2"),
    "1439": ("Manufacture of other knitted and crocheted apparel", "C", "2"),
    "1610": ("Sawmilling and planing of wood", "C", "2"),
    "1629": ("Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials", "C", "2"),
    "1729": ("Manufacture of other articles of paper and paperboard", "C", "2"),
    "2052": ("Manufacture of glues", "C", "2"),
    "2053": ("Manufacture of essential oils", "C", "2"),
    "2219": ("Manufacture of other rubber products", "C", "2"),
    "2229": ("Manufacture of other plastic products", "C", "2"),
    "2319": ("Manufacture and processing of other glass, including technical glassware", "C", "2"),
    "2349": ("Manufacture of other ceramic products", "C", "2"),
    "2369": ("Manufacture of other articles of concrete, plaster and cement", "C", "2"),
    "2529": ("Manufacture of other tanks, reservoirs and containers of metal", "C", "2"),
    "2550": ("Forging, pressing, stamping and roll-forming of metal; powder metallurgy", "C", "2"),
    "257": ("Manufacture of cutlery, tools and general hardware", "C", "2"),
    "2571": ("Manufacture of cutlery", "C", "2"),
    "2572": ("Manufacture of locks and hinges", "C", "2"),
    "2573": ("Manufacture of tools", "C", "2"),
    "268": ("Manufacture of magnetic and optical media", "C", "2"),
    "2680": ("Manufacture of magnetic and optical media", "C", "2"),
    "2849": ("Manufacture of other machine tools", "C", "2"),
    "3030": ("Manufacture of air and spacecraft and related machinery", "C", "2"),
    "3101": ("Manufacture of office and shop furniture", "C", "2"),
    "3102": ("Manufacture of kitchen furniture", "C", "2"),
    "3103": ("Manufacture of mattresses", "C", "2"),
    "3109": ("Manufacture of other furniture", "C", "2"),
    "411": ("Development of building projects", "F", "2"),
    "4110": ("Development of building projects", "F", "2"),
    "412": ("Construction of residential and non-residential buildings", "F", "2"),
    "4120": ("Construction of residential and non-residential buildings", "F", "2"),
    "4329": ("Other construction installation", "F", "2"),
    "4339": ("Other building completion and finishing", "F", "2"),
    "45": ("Wholesale and retail trade and repair of motor vehicles and motorcycles", "G", "2"),
    "451": ("Sale of motor vehicles", "G", "2"),
    "4511": ("Sale of cars and light motor vehicles", "G", "2"),
    "4519": ("Sale of other motor vehicles", "G", "2"),
    "452": ("Maintenance and repair of motor vehicles", "G", "2"),
    "4520": ("Maintenance and repair of motor vehicles", "G", "2"),
    "453": ("Sale of motor vehicle parts and accessories", "G", "2"),
    "4531": ("Wholesale trade of motor vehicle parts and accessories", "G", "2"),
    "4532": ("Retail trade of motor vehicle parts and accessories", "G", "2"),
    "454": ("Sale, maintenance and repair of motorcycles and related parts and accessories", "G", "2"),
    "4540": ("Sale, maintenance and repair of motorcycles and related parts and accessories", "G", "2"),
    "4651": ("Wholesale of computers, computer peripheral equipment and software", "G", "2"),
    "4652": ("Wholesale of electronic and telecommunications equipment and parts", "G", "2"),
    "4665": ("Wholesale of office furniture", "G", "2"),
    "4666": ("Wholesale of other office machinery and equipment", "G", "2"),
    "4669": ("Wholesale of other machinery and equipment", "G", "2"),
    "4674": ("Wholesale of hardware, plumbing and heating equipment and supplies", "G", "2"),
    "4675": ("Wholesale of chemical products", "G", "2"),
    "4676": ("Wholesale of other intermediate products", "G", "2"),
    "4677": ("Wholesale of waste and scrap", "G", "2"),
    "4719": ("Other retail sale in non-specialised stores", "G", "2"),
    "4729": ("Other retail sale of food in specialised stores", "G", "2"),
    "4741": ("Retail sale of computers, peripheral units and software in specialised stores", "G", "2"),
    "4742": ("Retail sale of telecommunications equipment in specialised stores", "G", "2"),
    "4743": ("Retail sale of audio and video equipment in specialised stores", "G", "2"),
    "4759": ("Retail sale of furniture, lighting equipment and other household articles in specialised stores", "G", "2"),
    "4765": ("Retail sale of games and toys in specialised stores", "G", "2"),
    "4789": ("Retail sale via stalls and markets of other goods", "G", "2"),
    "4799": ("Other retail sale not in stores, stalls or markets", "G", "2"),
    "4910": ("Passenger rail transport, interurban", "H", "2"),
    "5229": ("Other transportation support activities", "H", "2"),
    "5610": ("Restaurants and mobile food service activities", "I", "2"),
    "5629": ("Other food service activities", "I", "2"),
    "5814": ("Publishing of journals and periodicals", "J", "2"),
    "613": ("Satellite telecommunications activities", "J", "2"),
    "6130": ("Satellite telecommunications activities", "J", "2"),
    "620": ("Computer programming, consultancy and related activities", "J", "2"),
    "6201": ("Computer programming activities", "J", "2"),
    "6202": ("Computer consultancy activities", "J", "2"),
    "6203": ("Computer facilities management activities", "J", "2"),
    "6209": ("Other information technology and computer service activities", "J", "2"),
    "6311": ("Data processing, hosting and related activities", "J", "2"),
    "6312": ("Web portals", "J", "2"),
    "6399": ("Other information service activities n.e.c.", "J", "2"),
    "6420": ("Activities of holding companies", "K", "2"),
    "6430": ("Trusts, funds and similar financial entities", "K", "2"),
    "6810": ("Buying and selling of own real estate", "L", "2"),
    "7021": ("Public relations and communication activities", "M", "2"),
    "7022": ("Business and other management consultancy activities", "M", "2"),
    "7211": ("Research and experimental development on biotechnology", "M", "2"),
    "7219": ("Other research and experimental development on natural sciences and engineering", "M", "2"),
    "7410": ("Specialised design activities", "M", "2"),
    "7490": ("Other professional, scientific and technical activities n.e.c.", "M", "2"),
    "7729": ("Renting and leasing of other personal and household goods", "N", "2"),
    "783": ("Other human resources provision", "N", "2"),
    "7830": ("Other human resources provision", "N", "2"),
    "801": ("Private security activities", "N", "2"),
    "8010": ("Private security activities", "N", "2"),
    "802": ("Security systems service activities", "N", "2"),
    "8020": ("Security systems service activities", "N", "2"),
    "803": ("Investigation activities", "N", "2"),
    "8030": ("Investigation activities", "N", "2"),
    "8129": ("Other cleaning activities", "N", "2"),
    "8211": ("Combined office administrative service activities", "N", "2"),
    "8219": ("Photocopying, document preparation and other specialised office support activities", "N", "2"),
    "8541": ("Post-secondary non-tertiary education", "P", "2"),
    "8542": ("Tertiary education", "P", "2"),
    "8560": ("Educational support activities", "P", "2"),
    "8690": ("Other human health activities", "Q", "2"),
    "8790": ("Other residential care activities", "Q", "2"),
    "900": ("Creative, arts and entertainment activities", "R", "2"),
    "9001": ("Performing arts", "R", "2"),
    "9002": ("Support activities to performing arts", "R", "2"),
    "9003": ("Artistic creation", "R", "2"),
    "9004": ("Operation of arts facilities", "R", "2"),
    "910": ("Libraries, archives, museums and other cultural activities", "R", "2"),
    "9101": ("Library and archives activities", "R", "2"),
    "9102": ("Museums activities", "R", "2"),
    "9103": ("Operation of historical sites and buildings and similar visitor attractions", "R", "2"),
    "9104": ("Botanical and zoological gardens and nature reserves activities", "R", "2"),
    "9511": ("Repair of computers and peripheral equipment", "S", "2"),
    "9512": ("Repair of communication equipment", "S", "2"),
    "960": ("Other personal service activities", "S", "2"),
    "9601": ("Washing and (dry-)cleaning of textile and fur products", "S", "2"),
    "9602": ("Hairdressing and other beauty treatment", "S", "2"),
    "9603": ("Funeral and related activities", "S", "2"),
    "9604": ("Physical well-being activities", "S", "2"),
    "9609": ("Other personal service activities n.e.c.", "S", "2"),
    "99": ("Activities of extraterritorial organisations and bodies", "U", "2"),
    "990": ("Activities of extraterritorial organisations and bodies", "U", "2"),
    "9900": ("Activities of extraterritorial organisations and bodies", "U", "2"),
}


def _zaznam(kod):
    """Zaznam pro nejdelsi prefix kodu, ktery je v nomenklature."""
    cislice = "".join(c for c in str(kod or "") if c.isdigit())
    for delka in range(min(len(cislice), 4), 1, -1):
        zaznam = NACE.get(cislice[:delka])
        if zaznam:
            return zaznam
    return None


def nazev(kod):
    """
    Uredni nazev cinnosti. Pokryva i narodni kody s cislici navic - britska
    UK SIC 2007 "62012" i nemecka WZ "62.01.0" vedou na tridu NACE "6201".
    """
    zaznam = _zaznam(kod)
    return zaznam[0] if zaznam else ""


def revize(kod):
    """'2.1' | '2' - ze ktere revize kod pochazi, '' u neznameho."""
    zaznam = _zaznam(kod)
    return zaznam[2] if zaznam else ""


def uroven(kod):
    """'divize' | 'skupina' | 'trida' podle poctu cislic, '' u neznameho kodu."""
    kod = str(kod or "")
    return {2: "divize", 3: "skupina", 4: "trida"}.get(len(kod), "") if kod in NACE else ""


def vsechny(pocet_cislic=None):
    """Serazeny seznam (kod, nazev, sekce, revize); pocet_cislic omezi uroven."""
    return [(k, v[0], v[1], v[2]) for k, v in sorted(NACE.items())
            if pocet_cislic is None or len(k) == pocet_cislic]
